### ISSUE TITLE
Homepage not in DEP-12

### ISSUE THREAD

**Issue by ottok** [jelmer/upstream-ontologist#363]
Unlike the README states, the `Homepage` field isn't actually in https://dep-team.pages.debian.net/deps/dep12/

Using it will cause Lintian to nag:

    W: xtruss source: upstream-metadata-field-unknown Homepage [debian/upstream/metadata]
    N: 
    N:   The named field in the upstream metadata provided with this package is not
    N:   part of the DEP-12 specification.
    N:   
    N:   Please use only recognized field names.
    N: 
    N:   Please refer to https://dep-team.pages.debian.net/deps/dep12/ and
    N:   https://wiki.debian.org/UpstreamMetadata for details.
    N: 
    N:   Visibility: warning
    N:   Show-Always: no
    N:   Check: debian/upstream/metadata

**Comment by jelmer** [comment]
This is expected behaviour - the output is loosely inspired by DEP-12 as documented in the README, but it's not exactly DEP-12. If you want to have debian/upstream/metadata automatically generated then lintian-brush can do that for you.

**Comment by ottok** [comment]
Well, the README has a section titled `Extensions for upstream-ontologist, not defined in DEP-12:` and this `Homepage` isn't there, so it was confusing.

**Comment by jelmer** [comment]
Ah, I see what you mean now. Fixed in https://github.com/jelmer/upstream-ontologist/pull/369
