### ISSUE TITLE
python3-upstream-ontologist: should depend on python3-ruamel.yaml and python3-breezy

### ISSUE THREAD

**Issue by DataCrusade1999** [jelmer/upstream-ontologist#64]
Hi since there isn't a discussion tab I had to open an issue, I found this issue on the bug tracking system https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1029750 I would like to work on it but I could not setup my development environment as I'm using a Windows machine with WSL enabled could you guide me to setup the development environment and mentor me into resolving this bug as I'm fairly new to Debian. Here is the list of things that I've done till now

- subscribed to the relevant mailing lists
- understood the bug-tracking system
- asked #debian-mentors on IRC how to set up the dev environment and they told me to use sbuild for building the package and docker for testing. but I don't know how to reproduce the error on WSL(Ubuntu).

so as of now, I need help setting up my dev environment and reproducing the error.
thanks and apologies if this isn't the right way to ask for help

**Comment by jelmer** [comment]
The dependency on breezy and ruamel.yaml is actually present in pip (see https://github.com/jelmer/upstream-ontologist/blob/a8c8fa9ae16e2074995bc574f3ffd74a816a80dc/setup.cfg#L23), so this is not a bug that's relevant in this repository. You want to ask specifically on the Debian bug.

**Comment by jelmer** [comment]
I've just commented on the Debian bug.

**Comment by DataCrusade1999** [comment]
thanks for clarification
